version: '3.8'
services:
  product-catalog-api:
    build: ./backend/product-catalog-api
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
  order-api:
    build: ./backend/order-api
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
  cart-api:
    build: ./backend/cart-api
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  user-service:
    build: ./backend/user-service
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - product-catalog-api
      - order-api
      - cart-api
      - user-service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"   # Changed host port to 5673
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
volumes:
  mongo-data:
  redis-data:
