version: '3.8'
services:
  cart-api:
    build: ./backend/cart-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  order-api:
    build: ./backend/order-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
  product-catalog-api:
    build: ./backend/product-catalog-api
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
  user-service:
    build: ./backend/user-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - cart-api
      - order-api
      - product-catalog-api
      - user-service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
networks:
  default:
    driver: bridge
