version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: strapi-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ShopashoesDB
      MYSQL_USER: selerqc
      MYSQL_PASSWORD: selerqc
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: